### ISSUE TITLE
From "name" possible instead of from email?

### ISSUE THREAD

**Issue by satb** [mailman-elixir/mailman#53]
Is it possible to send the email such that the receiver see's the from name instead of the from email address?

Something like this:

`
"John Smith <john@company.com>"
`
This format is resulting in mailman completely dropping the email delivery.

I'll try taking a look if I can get a pointer (if it is possible)

**Comment by satb** [comment]
I came across this issue - https://github.com/kamilc/mailman/pull/29/files
But this is not working for me. I am using SES and it supports the format 

```
From: "Andrew" <andrew@example.com>;
```
However, sending it this way is resulting in the email not even being delivered. Not sure if it is mailman that is dropping it or SES.

**Comment by skosch** [comment]
@satb I know it's been a while – have you found a solution to this issue? The `"John Smith <john@company.com>"` format works fine for me personally. I wonder if this has to do with gen_smtp or even with your SMTP relay? Can we get to the bottom of this?

**Comment by satb** [comment]
@skosch - I moved to Bamboo ever since. You have to write your own SES adapter but its no big deal to write that. Bamboo is well designed and works well. I'd recommend that one. It has worked well for me - https://github.com/thoughtbot/bamboo

**Comment by skosch** [comment]
@satb Great! Mailman still has other features I need (in my case, attachment management) that bamboo hasn't been able to provide me, so I'm helping to maintain this one for the time being :)

**Comment by satb** [comment]
@skosch - Attachments are supported in bamboo although I didn't use it for my use case. 

https://github.com/thoughtbot/bamboo/blob/master/lib/bamboo/attachment.ex

Another option is to include a link to S3 in the email and push your attachment to S3.

**Comment by nandorstanko** [comment]
@skosch Do you know maybe what was the reason behind this change: https://github.com/mailman-elixir/mailman/commit/5ef8d931132c0814cb03db743ee74f76004978cb ? The `"John Smith <john@company.com>"` format was working before this, but now it accepts only the `"john@company.com"` format, as the email.from is not "cleaned" from the name part. I made a custom adapter, so I've managed to make this work, but still I'm curious...
