### ISSUE TITLE
These compiling warnings should be resolved, thanks.

### ISSUE THREAD

**Issue by tianjianyong** [mailman-elixir/mailman#57]
==> mailman
warning: the dependency :mailman requires Elixir "~> 1.0.0" but you are running on v1.3.3
Compiling 17 files (.ex)
warning: redefining @doc attribute previously set at line 3
  lib/mailman.ex:8: Mailman (module)

warning: parentheses are required when piping into a function call. For example:

```
foo 1 |> bar 2 |> baz 3
```

is ambiguous and should be written as

```
foo(1) |> bar(2) |> baz(3)
```

Ambiguous pipe found at:
  lib/mailman/parsing.ex:89

warning: parentheses are required when piping into a function call. For example:

```
foo 1 |> bar 2 |> baz 3
```

is ambiguous and should be written as

```
foo(1) |> bar(2) |> baz(3)
```

Ambiguous pipe found at:
  lib/mailman/parsing.ex:111

warning: parentheses are required when piping into a function call. For example:

```
foo 1 |> bar 2 |> baz 3
```

is ambiguous and should be written as

```
foo(1) |> bar(2) |> baz(3)
```

Ambiguous pipe found at:
  lib/mailman/parsing.ex:115

warning: parentheses are required when piping into a function call. For example:

```
foo 1 |> bar 2 |> baz 3
```

is ambiguous and should be written as

```
foo(1) |> bar(2) |> baz(3)
```

Ambiguous pipe found at:
  lib/mailman/parsing.ex:119

warning: parentheses are required when piping into a function call. For example:

```
foo 1 |> bar 2 |> baz 3
```

is ambiguous and should be written as

```
foo(1) |> bar(2) |> baz(3)
```

Ambiguous pipe found at:
  lib/mailman/render.ex:95

warning: parentheses are required when piping into a function call. For example:

```
foo 1 |> bar 2 |> baz 3
```

is ambiguous and should be written as

```
foo(1) |> bar(2) |> baz(3)
```

Ambiguous pipe found at:
  lib/mailman/render.ex:119

warning: parentheses are required when piping into a function call. For example:

```
foo 1 |> bar 2 |> baz 3
```

is ambiguous and should be written as

```
foo(1) |> bar(2) |> baz(3)
```

Ambiguous pipe found at:
  lib/mailman/render.ex:111

warning: redefining @doc attribute previously set at line 8
  lib/mailman.ex:13: Mailman (module)

Generated mailman app

**Comment by vasspilka** [comment]
I don't get these warnings when compiled with `mix compile`.
I do however get these 4 

```
warning: variable pending_lnb is unused
  lib/earmark/helpers/lookahead_helpers.ex:34

warning: unused import Earmark.Helpers.StringHelpers
  lib/earmark/helpers/lookahead_helpers.ex:7

warning: variable pure_from is unused
  lib/mailman/external_smtp_adapter.ex:31

warning: variable uri is unused
  lib/mailman/attachment.ex:688
```


Using:
Erlang/OTP 19 [erts-8.1.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]
Elixir 1.3.4

**Comment by skosch** [comment]
The warnings are gone, but code style is still a problem. I'm going to open a new issue. Thanks for reporting this nonetheless!
