### ISSUE TITLE
Custom email header support

### ISSUE THREAD

**Issue by vishal-h** [mailman-elixir/mailman#65]
Support custom Email headers like
ADD THE FOLLOWING HEADER TO THE EMAIL, "X-MAILGUN-VARIABLES: {"MY_MESSAGE_ID": 123}".

Taken from
http://resources.mailgun.com/webhooks.html

**Comment by ryanpager** [comment]
I would also need this as well -- is this possible using the library?

**Comment by lessless** [comment]
This is something we need too!

**Comment by skosch** [comment]
Custom email headers are now supported in master! Please give it a try and let us know if it works for you.
