### ISSUE TITLE
Does Mailman need help or a new home?

### ISSUE THREAD

**Issue by Ch4s3** [mailman-elixir/mailman#68]
@kamilc I'm using a fork of mailman at the moment to get it working, but I'm not sure that's sustainable. Do you need help maintaining the package? I'd be happy to pitch in here an triage PRs.

**Comment by skosch** [comment]
@Ch4s3 It doesn't look you have your fork public on github, but I'd love to take a look at it. Having written a bunch of custom code myself to sidestep some of Mailman's issues, I totally agree that this is an important package and that it could use some TLC :)

**Comment by kamilc** [comment]
@Ch4s3 @skosch I agree that Mailman needs a helping hand. Sorry for keeping this ticket unresponded for so long. Would you guys be willing to get involved as collaborators and handle the PR's, fixes etc?

**Comment by skosch** [comment]
@kamilc Thank you for the offer. I can't make any promises as to the extent of my contributions for the next half year or so, but I'm happy to help where I can, sure! I think just looking through the open issues as well as existing forks will turn up a lot of small, easy fixes.

**Comment by Ch4s3** [comment]
I'll put up a fork soon, and tag you all in. Sorry for the delay, I was on vacation.

**Comment by kamilc** [comment]
@skosch @Ch4s3 I've just sent you invites to become collaborators. I'll need to double check the repo settings to be sure you have all the control you'll need. Thanks for your help!

**Comment by skosch** [comment]
Thank you @kamilc. The next two months are looking pretty rough for me work-wise but I anticipate being able to help out more in the fall :)

**Comment by kamilc** [comment]
@skosch No worries, and Thanks again!

**Comment by Ch4s3** [comment]
I'll take a look as soon as I can!
