### ISSUE TITLE
Moving to organization based repo

### ISSUE THREAD

**Issue by kamilc** [mailman-elixir/mailman#71]
@skosch @Ch4s3 

I figured that keeping the project under my account could be misleading as to the origins of efforts from now on. Because of this, I've just created a new organization in GitHub for the project and invited you both: mailman-elixir.

The repo has been cloned over there and lives at: https://github.com/mailman-elixir/mailman

Could you please make sure you have the needed access? It's becoming **our** baby from now on :)

**Comment by skosch** [comment]
That's really sweet. :) I think there's a way to transfer a repo to a new owner, including all issues and stars etc. I would suggest you scrap the cloned repo and then transfer this one over (I think there's a button in your repo settings).

**Comment by skosch** [comment]
@kamilc sorry to bug you again – do you think you could look into this and #70 sometime?

**Comment by kamilc** [comment]
@skosch Its not a bother - I will take a look as soon as I'm out of the hospital (most probably beginning of the next week). Sorry for the delay

**Comment by skosch** [comment]
Oh no! In that case, take your time :anguished: hope you're doing okay!

**Comment by kamilc** [comment]
It was a pretty light surgery - I'm doing just fine :)

So as you can see I transferred the repo to our organization (Thanks for the suggestion - I wasn't aware that we can do that). I've also took a look at the inline images branch and updated the ticket for my comments.

**Comment by skosch** [comment]
Excellent, thank you, and I hope you'll be back on your feet soon! I think we can close this thread then :)
