### ISSUE TITLE
Deprecated Httpotion

### ISSUE THREAD

**Issue by karlseguin** [mailman-elixir/mailman#87]
Httpotion is now deprecated. It's a shame to have this dependency in Mailman. Any chance to remove it with something that's still maintained.

Even better would be to make the attachement downloading module (or function) configurable.

**Comment by skosch** [comment]
Thanks @karlseguin, I wasn't aware of the deprecation. I won't be able to take this on within the next few weeks, but would be grateful for PRs :)

**Comment by skosch** [comment]
The `next` branch uses HTTPoison instead, which is still maintained. We'll switch to that one as soon as the next release of gen_smtp is out.
