### ISSUE TITLE
How to add dep to mix.exs

### ISSUE THREAD

**Issue by packetq** [mailman-elixir/mailman#95]
Hi,

I'm new to Elixir. How do I add this package to the deps in mix.exs?

Thanks

**Comment by skosch** [comment]
For the current version, you can see the line you need on the [hex.pm](https://hex.pm/packages/mailman) page:
```elixir
{:mailman, "~> 0.4.3"},
```

**Comment by packetq** [comment]
Hi,

Thanks!
